on: push

jobs:
  init:
    name: initialize
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: run tests
      run: make run
